# Generated by Django 5.0.7 on 2026-02-04 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0012_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='Phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='Total_person',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='User_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='Category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Base_App.itemlist'),
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_App.items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Base_App.order')),
            ],
        ),
    ]
